pool:
  vmImage: 'Ubuntu 16.04'
strategy:
  matrix:
    Python36:
      PYTHON_VERSION: '3.6'

steps:
  - script: python3 -m pip install --upgrade pip setuptools
    displayName: 'Install python tools'
  - script: |
      source install.sh
    displayName: 'Install dependencies'
  # Download Secure File
  # Download a secure file to a temporary location on the build or release agent
  - task: DownloadSecureFile@1
    inputs:
      secureFile: initialize_remote.sh
      secureFile: remote.yml
  - script: |
      cd test
      cp $(Agent.TempDirectory)/initialize_remote.sh .
      cp $(Agent.TempDirectory)/remote.yml naive_test/
      source initialize_remote.sh
    displayName: 'Install dependencies in remote machine'
  - script: |
      cd test
      export PATH=$HOME/.local/bin:$PATH
      python3 naive_test.py
    displayName: 'Integration tests'
  - script: |
      cd test
      export PATH=$HOME/.local/bin:$PATH
      python3 sdk_tuner_test.py
    displayName: 'Built-in tuner tests'
