jobs:

- job: 'Ubuntu_16_04'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'

  steps:
  - script: |
      echo $(Release.ReleaseWebURL)
  #- script: python3 -m pip install --upgrade pip setuptools
  #  displayName: 'Install python tools'
  #- script: |
  #    source install.sh
  #  displayName: 'Install nni toolkit via source code'
  #- task: DownloadSecureFile@1
  #  inputs:
  #    secureFile: id_rsa
  #- script: |
  #    cd test && cp $(Agent.TempDirectory)/id_rsa ./id_rsa
  #    chmod 600 ./id_rsa
  #  displayName: 'Download secure file'
  #- task: CopyFilesOverSSH@0
  #  inputs:
  #    sshEndpoint: remote241
  #    sourceFolder: src/sdk/pynni
  #    targetFolder: ~/pynni
  #    overwrite: true
  #  displayName: 'Copy sdk to remote machine'
  #- task: SSH@0
  #  inputs:
  #    sshEndpoint: remote241
  #    runOptions: script
  #    scriptPath: install_sdk_remote.sh
  #  displayName: 'Install sdk in remote machine'
  #- script: |
  #    cd test
  #    PATH=$HOME/.local/bin:$PATH python3 naive_test.py
  #  displayName: 'Integration tests'
  #- script: |
  #    cd test
  #    PATH=$HOME/.local/bin:$PATH python3 sdk_test.py
  #  displayName: 'Built-in tuner tests'


- job: 'macOS_10_13'
  pool:
    vmImage: 'macOS 10.13'
  strategy:
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'

  steps:
  - script: python3 -m pip install --upgrade pip setuptools
    displayName: 'Install python tools'
  - script: |
      source install.sh
    displayName: 'Install nni toolkit via source code'
  - script: |
      cd test
      PATH=$HOME/Library/Python/3.7/bin:$PATH python3 naive_test.py
    displayName: 'Integration tests'
  - script: |
      cd test
      PATH=$HOME/Library/Python/3.7/bin:$PATH python3 sdk_test.py
    displayName: 'Built-in tuner tests'