jobs:
- job: 'Ubuntu_16_04_remote'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'

  steps:
  - script: python3 -m pip install --upgrade pip setuptools
    displayName: 'Install python tools'
  - script: |
      source install.sh
    displayName: 'Install nni toolkit via source code'
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: remote_139
      sourceFolder: src/sdk/pynni
      targetFolder: /tmp/nnitest/$(Build.BuildId)/pynni
      overwrite: true
    displayName: 'Copy sdk files to remote machine'
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: remote_139
      sourceFolder: test
      targetFolder: /tmp/nnitest/$(Build.BuildId)/test
      overwrite: true
    displayName: 'Copy test files to remote machine'
  - task: SSH@0
    inputs:
      sshEndpoint: remote_139
      runOptions: commands
      commands: python3 /tmp/nnitest/$(Build.BuildId)/test/remote_docker.py --mode start --name $(Build.BuildId) --image nni/nni
    displayName: 'Start docker'
  # - task: DownloadSecureFile@1
  #   inputs:
  #     secureFile: id_rsa
  - script: |
      # mkdir ~/.ssh
      # ssh-keyscan 23.96.57.139 >> ~/.ssh/known_hosts
      # cp $(Agent.TempDirectory)/id_rsa test/id_rsa
      # chmod 600 test/id_rsa
      $(docker_pwd) | ssh root@23.96.57.139 -p 22 "cat /tmp/nnitest/$(Build.BuildId)/port" > test/port
      cat test/port
    displayName: 'Get docker port'
  - script: |
      cd test
      PATH=$HOME/.local/bin:$PATH  docker_port=${cat port} docker_user=$(docker_user) docker_pwd=$(docker_pwd) python3 config_test.py --ts remote
    displayName: 'Built-in dispatcher tests'
  - task: SSH@0
    inputs:
      sshEndpoint: remote_139
      runOptions: commands
      commands: python3 /tmp/nnitest/$(Build.BuildId)/test/remote_docker.py --mode stop --name $(Build.BuildId)
    displayName: 'Stop docker'
    