jobs:

- job: 'Ubuntu_16_04'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'

  steps:
  #- script: python3 -m pip install --upgrade pip setuptools
  #  displayName: 'Install python tools'
  #- script: |
  #    source install.sh
  #  displayName: 'Install nni toolkit via source code'
  - task: DownloadSecureFile@1
    inputs:
      secureFile: id_rsa
  - script: |
      cd test && cp $(Agent.TempDirectory)/id_rsa ./id_rsa
      ip="nni@104.210.63.241"
      key="id_rsa"
      #chmod 600 $key
      echo "Initializing remote machine..."
      ssh -i $key $ip "rm -rf pynni"
      #source initialize_remote.sh
    displayName: 'Install dependencies in remote machine'
  #- script: |
  #    cd test
  #    PATH=$HOME/.local/bin:$PATH python3 naive_test.py
  #  displayName: 'Integration tests'
  #- script: |
  #    cd test
  #    PATH=$HOME/.local/bin:$PATH python3 sdk_test.py
  #  displayName: 'Built-in tuner tests'

- job: 'macOS_10_13'
  pool:
    vmImage: 'macOS 10.13'
  strategy:
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'

  steps:
  - script: python3 -m pip install --upgrade pip setuptools
    displayName: 'Install python tools'
  - script: |
      source install.sh
    displayName: 'Install nni toolkit via source code'
  - script: |
      cd test
      PATH=$HOME/Library/Python/3.7/bin:$PATH python3 naive_test.py
    displayName: 'Integration tests'
  - script: |
      cd test
      PATH=$HOME/Library/Python/3.7/bin:$PATH python3 sdk_test.py
    displayName: 'Built-in tuner tests'